// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module security_island_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 5
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output security_island_reg_pkg::security_island_reg2hw_t reg2hw, // Write
  input  security_island_reg_pkg::security_island_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import security_island_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [BlockAw-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic pulp_cluster_fetch_en_qs;
  logic pulp_cluster_fetch_en_wd;
  logic pulp_cluster_fetch_en_we;
  logic pulp_cluster_eoc_qs;
  logic cl_clk_en_qs;
  logic cl_clk_en_wd;
  logic cl_clk_en_we;
  logic [31:0] cl_clk_div_value_qs;
  logic [31:0] cl_clk_div_value_wd;
  logic cl_clk_div_value_we;
  logic [31:0] ot_clk_div_value_qs;
  logic [31:0] ot_clk_div_value_wd;
  logic ot_clk_div_value_we;

  // Register instances
  // R[pulp_cluster_fetch_en]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_pulp_cluster_fetch_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (pulp_cluster_fetch_en_we),
    .wd     (pulp_cluster_fetch_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.pulp_cluster_fetch_en.q ),

    // to register interface (read)
    .qs     (pulp_cluster_fetch_en_qs)
  );


  // R[pulp_cluster_eoc]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_pulp_cluster_eoc (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.pulp_cluster_eoc.de),
    .d      (hw2reg.pulp_cluster_eoc.d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (pulp_cluster_eoc_qs)
  );


  // R[cl_clk_en]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_cl_clk_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cl_clk_en_we),
    .wd     (cl_clk_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cl_clk_en.q ),

    // to register interface (read)
    .qs     (cl_clk_en_qs)
  );


  // R[cl_clk_div_value]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h1)
  ) u_cl_clk_div_value (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cl_clk_div_value_we),
    .wd     (cl_clk_div_value_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (reg2hw.cl_clk_div_value.qe),
    .q      (reg2hw.cl_clk_div_value.q ),

    // to register interface (read)
    .qs     (cl_clk_div_value_qs)
  );


  // R[ot_clk_div_value]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h1)
  ) u_ot_clk_div_value (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ot_clk_div_value_we),
    .wd     (ot_clk_div_value_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (reg2hw.ot_clk_div_value.qe),
    .q      (reg2hw.ot_clk_div_value.q ),

    // to register interface (read)
    .qs     (ot_clk_div_value_qs)
  );




  logic [4:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == SECURITY_ISLAND_PULP_CLUSTER_FETCH_EN_OFFSET);
    addr_hit[1] = (reg_addr == SECURITY_ISLAND_PULP_CLUSTER_EOC_OFFSET);
    addr_hit[2] = (reg_addr == SECURITY_ISLAND_CL_CLK_EN_OFFSET);
    addr_hit[3] = (reg_addr == SECURITY_ISLAND_CL_CLK_DIV_VALUE_OFFSET);
    addr_hit[4] = (reg_addr == SECURITY_ISLAND_OT_CLK_DIV_VALUE_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(SECURITY_ISLAND_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(SECURITY_ISLAND_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(SECURITY_ISLAND_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(SECURITY_ISLAND_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(SECURITY_ISLAND_PERMIT[4] & ~reg_be)))));
  end

  assign pulp_cluster_fetch_en_we = addr_hit[0] & reg_we & !reg_error;
  assign pulp_cluster_fetch_en_wd = reg_wdata[0];

  assign cl_clk_en_we = addr_hit[2] & reg_we & !reg_error;
  assign cl_clk_en_wd = reg_wdata[0];

  assign cl_clk_div_value_we = addr_hit[3] & reg_we & !reg_error;
  assign cl_clk_div_value_wd = reg_wdata[31:0];

  assign ot_clk_div_value_we = addr_hit[4] & reg_we & !reg_error;
  assign ot_clk_div_value_wd = reg_wdata[31:0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = pulp_cluster_fetch_en_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = pulp_cluster_eoc_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[0] = cl_clk_en_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = cl_clk_div_value_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[31:0] = ot_clk_div_value_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module security_island_reg_top_intf
#(
  parameter int AW = 5,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output security_island_reg_pkg::security_island_reg2hw_t reg2hw, // Write
  input  security_island_reg_pkg::security_island_hw2reg_t hw2reg, // Read
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  security_island_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .hw2reg, // Read
    .devmode_i
  );
  
endmodule


