// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package security_island_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 5;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic        q;
  } security_island_reg2hw_pulp_cluster_fetch_en_reg_t;

  typedef struct packed {
    logic        q;
  } security_island_reg2hw_cl_clk_en_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        qe;
  } security_island_reg2hw_cl_clk_div_value_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        qe;
  } security_island_reg2hw_ot_clk_div_value_reg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } security_island_hw2reg_pulp_cluster_eoc_reg_t;

  // Register -> HW type
  typedef struct packed {
    security_island_reg2hw_pulp_cluster_fetch_en_reg_t pulp_cluster_fetch_en; // [67:67]
    security_island_reg2hw_cl_clk_en_reg_t cl_clk_en; // [66:66]
    security_island_reg2hw_cl_clk_div_value_reg_t cl_clk_div_value; // [65:33]
    security_island_reg2hw_ot_clk_div_value_reg_t ot_clk_div_value; // [32:0]
  } security_island_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    security_island_hw2reg_pulp_cluster_eoc_reg_t pulp_cluster_eoc; // [1:0]
  } security_island_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] SECURITY_ISLAND_PULP_CLUSTER_FETCH_EN_OFFSET = 5'h 0;
  parameter logic [BlockAw-1:0] SECURITY_ISLAND_PULP_CLUSTER_EOC_OFFSET = 5'h 4;
  parameter logic [BlockAw-1:0] SECURITY_ISLAND_CL_CLK_EN_OFFSET = 5'h 8;
  parameter logic [BlockAw-1:0] SECURITY_ISLAND_CL_CLK_DIV_VALUE_OFFSET = 5'h c;
  parameter logic [BlockAw-1:0] SECURITY_ISLAND_OT_CLK_DIV_VALUE_OFFSET = 5'h 10;

  // Register index
  typedef enum int {
    SECURITY_ISLAND_PULP_CLUSTER_FETCH_EN,
    SECURITY_ISLAND_PULP_CLUSTER_EOC,
    SECURITY_ISLAND_CL_CLK_EN,
    SECURITY_ISLAND_CL_CLK_DIV_VALUE,
    SECURITY_ISLAND_OT_CLK_DIV_VALUE
  } security_island_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] SECURITY_ISLAND_PERMIT [5] = '{
    4'b 0001, // index[0] SECURITY_ISLAND_PULP_CLUSTER_FETCH_EN
    4'b 0001, // index[1] SECURITY_ISLAND_PULP_CLUSTER_EOC
    4'b 0001, // index[2] SECURITY_ISLAND_CL_CLK_EN
    4'b 1111, // index[3] SECURITY_ISLAND_CL_CLK_DIV_VALUE
    4'b 1111  // index[4] SECURITY_ISLAND_OT_CLK_DIV_VALUE
  };

endpackage

