// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"data_mem", '{
        '{32'h00100000, 32'h001fffff}
    }},
    '{"sim_ctrl", '{
        '{32'h00020000, 32'h00020fff}
    }},
    '{"rom_ctrl", '{
        '{32'h411e0000, 32'h411e0fff}
    }},
    '{"kmac", '{
        '{32'h41120000, 32'h41120fff}
    }},
    '{"keymgr", '{
        '{32'h41130000, 32'h41130fff}
    }},
    '{"otp_ctrl", '{
        '{32'h40130000, 32'h40130fff}
    }},
    '{"hmac", '{
        '{32'h41110000, 32'h41110fff}
    }},
    '{"lc_ctrl", '{
        '{32'h40140000, 32'h40140fff}
    }},
    '{"sram_ctrl", '{
        '{32'h411c0000, 32'h411c0fff}
    }},
    '{"flash_ctrl", '{
        '{32'h41000000, 32'h41000fff}
    }},
    '{"uart", '{
        '{32'h40000000, 32'h40000fff}
    }},
    '{"clkmgr", '{
        '{32'h40420000, 32'h40420fff}
    }},
    '{"sysrst_ctrl", '{
        '{32'h40430000, 32'h40430fff}
    }},
    '{"rstmgr", '{
        '{32'h40410000, 32'h40410fff}
    }},
    '{"pwrmgr", '{
        '{32'h40400000, 32'h40400fff}
    }},
    '{"alert_handler", '{
        '{32'h40150000, 32'h40150fff}
    }},
    '{"rv_dm", '{
        '{32'h41200000, 32'h41200fff}
    }},
    '{"rv_plic", '{
        '{32'h41010000, 32'h41010fff}
    }},
    '{"edn", '{
        '{32'h41170000, 32'h41170fff}
    }},
    '{"otbn", '{
        '{32'h411d0000, 32'h411d0fff}
    }},
    '{"aes", '{
        '{32'h41100000, 32'h41100fff}
    }},
    '{"csrng", '{
        '{32'h41150000, 32'h41150fff}
    }},
    '{"entropy_src", '{
        '{32'h41160000, 32'h41160fff}
    }},
    '{"gpio", '{
        '{32'h40040000, 32'h40040fff}
    }},
    '{"spi_device", '{
        '{32'h40050000, 32'h40050fff}
    }},
    '{"spi_host", '{
        '{32'h40060000, 32'h40060fff}
    }},
    '{"instr_mem", '{
        '{32'h30120000, 32'h30120fff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"core_instr", 0, '{
    ,
    '{"core_data", 1, '{
        "data_mem",
        "sim_ctrl",
        "rom_ctrl",
        "kmac",
        "keymgr",
        "otp_ctrl",
        "hmac",
        "lc_ctrl",
        "sram_ctrl",
        "flash_ctrl",
        "uart",
        "clkmgr",
        "sysrst_ctrl",
        "rstmgr",
        "pwrmgr",
        "alert_handler",
        "rv_dm",
        "rv_plic",
        "edn",
        "otbn",
        "aes",
        "csrng",
        "entropy_src",
        "gpio",
        "spi_device",
        "spi_host"}}
};
