# Copyright 2024 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

"""Repository rule to dynamically locate Cheshire SW headers via the CHS_ROOT
environment variable, which is resolved by Bender in the parent (Carfield) build.

Usage in WORKSPACE:
    load("//rules:cheshire.bzl", "cheshire_sw_repo")
    cheshire_sw_repo(name = "cheshire_sw")

Then depend on it from a cc_library:
    deps = ["@cheshire_sw//:regs"]
"""

_BUILD_TEMPLATE = """\
# Auto-generated by rules/cheshire.bzl — do not edit.
cc_library(
    name = "regs",
    hdrs = glob(["regs/*.h"]),
    includes = ["."],
    copts = ["-fdebug-prefix-map={chs_root}/sw/include=external/cheshire_sw"],
    visibility = ["//visibility:public"],
)
"""

def _cheshire_sw_repo_impl(rctx):
    chs_root = rctx.os.environ.get("CHS_ROOT", "")
    if not chs_root:
        fail(
            "CHS_ROOT is not set in the environment. " +
            "It must point to the Cheshire repository root. " +
            "When building from Carfield, CHS_ROOT is resolved automatically " +
            "via `bender path cheshire` and passed to the OpenTitan sub-make. " +
            "For standalone builds, export CHS_ROOT=/path/to/cheshire before " +
            "invoking Bazel.",
        )

    # Symlink only the regs sub-directory so the sandbox stays minimal.
    rctx.symlink(chs_root + "/sw/include/regs", "regs")
    rctx.file("BUILD.bazel", _BUILD_TEMPLATE.format(chs_root = chs_root))

cheshire_sw_repo = repository_rule(
    implementation = _cheshire_sw_repo_impl,
    # Bazel re-evaluates the rule whenever this env var changes.
    environ = ["CHS_ROOT"],
    local = True,
    doc = "Exposes Cheshire SW register headers as a Bazel cc_library target.",
)
